export const ATTENDANCE_START_DIGITAL = 'ATTENDANCE_START_DIGITAL';
export const ATTENDANCE_STOP = 'ATTENDANCE_STOP';
export const ATTENDANCE_DROP = 'ATTENDANCE_DROP';
export const ATTENDANCE_LIST = 'ATTENDANCE_LIST';
export const ATTENDANCE_CHECK_LIST = 'ATTENDANCE_CHECK_LIST';