export const HOMEWORK_LIST = 'HOMEWORK_LIST';
export const HOMEWORK_POST = 'HOMEWORK_POST';
export const HOMEWORK_DELETE = 'HOMEWORK_DELETE';
export const HOMEWORK_EDIT = 'HOMEWORK_EDIT';
export const HOMEWORK_SUBMIT = 'HOMEWORK_SUBMIT';